spring:
    datasource:
        url: jdbc:h2:mem:short-url-db-dev
        driver-class-name: org.h2.Driver
        username: dev
        password:
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
